
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://ws.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Conversion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Conversion", targetNamespace = "http://ws.example.org/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "ConversionResponse", targetNamespace = "http://ws.example.org/", className = "proxy.ConversionResponse")
    @Action(input = "http://ws.example.org/BankService/ConversionRequest", output = "http://ws.example.org/BankService/ConversionResponse")
    public double conversion(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param id
     * @return
     *     returns proxy.Compte
     */
    @WebMethod(operationName = "GetCompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCompte", targetNamespace = "http://ws.example.org/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "GetCompteResponse", targetNamespace = "http://ws.example.org/", className = "proxy.GetCompteResponse")
    @Action(input = "http://ws.example.org/BankService/GetCompteRequest", output = "http://ws.example.org/BankService/GetCompteResponse")
    public Compte getCompte(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod(operationName = "CompteList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CompteList", targetNamespace = "http://ws.example.org/", className = "proxy.CompteList")
    @ResponseWrapper(localName = "CompteListResponse", targetNamespace = "http://ws.example.org/", className = "proxy.CompteListResponse")
    @Action(input = "http://ws.example.org/BankService/CompteListRequest", output = "http://ws.example.org/BankService/CompteListResponse")
    public List<Compte> compteList();

}
